### ISSUE TITLE
Update Package Settings

### ISSUE THREAD

**Issue by biohazard999** [JasonBock/Rocks#138]
The nuget package has a icon that is really hard to identitfy

What about a brand change: Compare those two:

![image](https://user-images.githubusercontent.com/653905/105147655-c6014900-5b01-11eb-8107-b4c907d082e2.png)

![image](https://user-images.githubusercontent.com/653905/105147575-ab2ed480-5b01-11eb-9f19-99544367d6ab.png)

Could be found in the [noun project](https://thenounproject.com/search/?q=rock&i=2070713)

**Comment by JasonBock** [comment]
I don't think I'd use the devil horns for Rocks, though I like the sentiment :). I've thought about creating icons for **all** of my NuGet packages to have a similar theme, but it's just too low on the priority list right now.

**Comment by JasonBock** [comment]
I'm still thinking about this :). The devil horns - aka "this rocks!" - is growing on me. I may alter it a bit so that it's easier to see on a dark theme. The one out of the box is **really** hard to see with a dark theme enabled.

**Comment by JasonBock** [comment]
OK, this is an issue with some package updates that I want to make, including the icon. Here's the list:

* Central package management
* Use a better icon
* XML comments + inclusion in the package
* Other things as I remember them
