### ISSUE TITLE
Build stalls when Rock attribute is duplicated in dependent project

### ISSUE THREAD

**Issue by mgurlitz** [JasonBock/Rocks#340]
**To Reproduce**
1. Create two .NET 8 class library projects
2. Add Rocks 8.3.0 library to both projects
3. Add a dependency from Project2 to Project1
4. Create an empty Class1 in Project1
5. Add `[assembly: Rock(typeof(Class1), BuildType.Create)]` or `RockCreate<Class1>` attribute to Project1
6. Add `[assembly: Rock(typeof(Class1), BuildType.Create)]` or `RockCreate<Class1>` attribute to Project2
7. Build Project2

**Expected behavior**
Either an error that there's a conflict, or a successful build

**Actual behavior**
The build stalls and doesn't complete after waiting several minutes

**Additional context**
- This is a regression from Rocks 8.1.0
- Occurs with .NET 8.0.401 as well as .NET 9 RC1
- Reproduces on Windows 11 and Ubuntu 22.04

**Workaround**
Use the InternalVisiblesTo attribute in Project1 to expose the Class1 mock to Project2

**Comment by JasonBock** [comment]
Huh, that's an interesting one. Glad that have a workaround 🙂. I'm busy this weekend, but I'll take a look at it when I get back. Thanks for reporting it.

**Comment by JasonBock** [comment]
OK, I **think** I have a fix in place. At least locally it doesn't spin out of control anymore like it does (which I think the bug came in with #288 in `8.2.0`, though I'm not 100% sure **why** it spins out of control with this). I'm going to do some more testing so I feel like it's doing what I expect it to do.

**Comment by JasonBock** [comment]
I've decided to close this bug as I think I got a fix in place.
