### ISSUE TITLE
Support CoreCLR

### ISSUE THREAD

**Issue by JasonBock** [JasonBock/Rocks#40]
There's no reason Rocks shouldn't run on CoreCLR, but ... make sure it does.

**Comment by JasonBock** [comment]
This may also be expanded to change Rocks to be a shared project, potentially targeting Windows 10 apps, CoreCLR, etc.

**Comment by NickolasAcosta** [comment]
[ApiPortAnalysis.xlsx](https://github.com/JasonBock/Rocks/files/233891/ApiPortAnalysis.xlsx)

Here is an analysis of the port to coreclr given the current codebase if anyone else is interested.

**Comment by JasonBock** [comment]
Here's the steps I think I need to follow:

* Update testing to xUnit. I believe NUnit works with .NET Core, but I know xUnit does, and it's not too painful to convert to xUnit
* Create shared projects for 
  * Rocks => Rocks.Shared
  * Rocks.Tests.Types => Rocks.Tests.Types.Shared 
  * Rocks.Tests => Rocks.Tests.Shared
* Create .NET versions using these shared projects
  * Rocks.NET (uses Rocks.Shared)
  * Rocks.Tests.Types.NET (uses Rocks.Tests.Types.Shared)
  * Rocks.Tests.NET (uses Rocks.Tests.Shared)
* Create .NET Core versions using these shared projects
  * Rocks.NETCore (uses Rocks.Shared)
  * Rocks.Tests.Types.NETCore (uses Rocks.Tests.Types.Shared)
  * Rocks.Tests.NETCore (uses Rocks.Tests.Shared)
* Then I can try that with the task
  * Shared
    * Rocks.Task.Shared
    * Rocks.RockAssemblyTestContainer.Shared
    * Rocks.Task.Tests.Shared
  * .NET
    * Rocks.Task.NET (uses Rocks.Task.Shared)
    * Rocks.RockAssemblyTestContainer.NET (uses Rocks.RockAssemblyTestContainer.Shared)
    * Rocks.Task.Tests.NET (uses Rocks.Task.Tests.Shared)
  * .NET Core
    * Rocks.Task.NETCore (uses Rocks.Task.Shared)
    * Rocks.RockAssemblyTestContainer.NETCore (uses Rocks.RockAssemblyTestContainer.Shared)
    * Rocks.Task.Tests.NETCore (uses Rocks.Task.Tests.Shared)
* Then do Rocks.PackageTest.NET and Rocks.PackageTest.NETCore (no shared project here)

Here are some potential hang-up points...

Serialization: .NET Core has no concept of binary serialization. I can use Json serialization via these two dependencies:

````
"System.Private.DataContractSerialization": "4.1.1",
"System.Runtime.Serialization.Json": "4.0.1"
`````

With something like this:

````
public class Data
{
	public int Value { get; set; }
}

var data = new Data { Value = 44 };
var serializer = new DataContractJsonSerializer(typeof(Data));

using (var stream = new MemoryStream())
{
	serializer.WriteObject(stream, data);
	stream.Position = 0;
	var newData = serializer.ReadObject(stream) as Data;
	Console.Out.WriteLine(newData.Value);
}
````

So I'd have to probably "partial" a bunch of types so they work correctly with serialization and that the tests work correctly. Also, the `Binder` property that uses `SerializationBinder` will probably not work in .NET Core so I may have to come up with a different approach....or maybe just dump serialization support with .NET Core. Some of the types within Rocks won't work as-is with JSON serialization.

Reflection: Any place I'm using `Type` I'll need to (probably) call `GetTypeInfo()`. Emitting an assembly and then loading it will require `AssemblyLoadContext`. So creating the `Assembly` will require a partial method approach to getting the assembly.

**Comment by JasonBock** [comment]
I may just end up changing Rocks to be .NET Standard 2.0. Not sure yet if that's the right way to go, but that may give the greatest flexibility and reach.

**Comment by JasonBock** [comment]
I just did an initial take on this. The Rocks.NETCore.sln file builds, but most of the tests fail for bizarre reasons. I'm going to talk to MS about this and see if they can help out because I'm kind of stuck at the moment :(
